global:
  scrape_interval: 60s


scrape_configs:
- job_name: 'minecraft'
  static_configs:
    - targets: ['minecraft:19565']
      labels:
        server_name: 'minecraft-docker'
  
- job_name: 'prometheus'
  static_configs:
    - targets: ['prometheus:9090']
